### PR TITLE
Update cache files

### LINKED ISSUE #10: Migrate cache files to Typescript
* **I'm submitting an ...**
  - [x] enhancement

* **What is the expected behavior?**
The current cache files were written in JavaScript. This proposes migrating them to TypeScript.

### PR DESCRIPTION
**Pull request by AitorDB**
#### Description
Updated cache JS files to TS files

#### Type of change
Please select the relevant option

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Others (cosmetics, styling, improvements)
- [ ] This change requires a documentation update

#### How Has This Been Tested?

- [ ] Unit
- [ ] Integration
- [ ] End-to-end

#### How to Test

This can be tested compiling TS

#### Any background context you want to add?

Closes https://github.com/Allan690/DevJobs-Slack-bot/issues/10

### CODE REVIEW

**Review by Allan690 — APPROVED** [review]
Looks good to me

**Review by Allan690 — COMMENTED** [review]
@AitorDB kindly squash all your future commits into a single commit

**Review by Allan690 — COMMENTED** [review]
@all-contributors please add @AitorDB for his contributions

**Review by danuluma — APPROVED** [review]
Looks good

**Pull request merged**
